server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: io.github.jotabrc
      client-id: c1
      auto-offset-reset: lastest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
  application:
    name: ov-saga-i
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:
  jpa:
    show-sql: true
    open-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enable: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
springdoc:
  api-docs:
    enable: true
    pth: /v3/api-docs
  swagger-ui:
    path: /swagger-ui

logging:
  level:
    io.lettuce.core: TRACE
    io.lettuce: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.servlet.DispatcherServlet: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.cache.interceptor: DEBUG
